background = 0xFF10141C
base = 0xFF171D29
text = 0xFFEAF2FF
alternate_base = 0xFF222B3A
bright_text = 0xFFFFFFFF
link_text = 0xFF8BD5FF
accent = 0xFF7AA2F7
accent_secondary = 0xFFC099FF

rounding_large = 18
rounding_small = 10

h1_size = 22
h2_size = 17
h3_size = 14
font_size = 13
small_font_size = 10

icon_theme = Adwaita
font_family = Adwaita Sans
font_family_monospace = FiraCode Nerd Font
