# Notifications (swaync)
bindd = SUPER, COMMA, Dismiss last notification, exec, swaync-client --close-latest
bindd = SUPER SHIFT, COMMA, Dismiss all notifications, exec, swaync-client --close-all
bindd = SUPER CTRL, COMMA, Open notifications panel, exec, swaync-client --toggle-panel
bindd = SUPER ALT, COMMA, Toggle silencing notifications, exec, swaync-client --toggle-dnd && swaync-client --get-dnd | grep -q 'true' && notify-send "Silenced notifications" || notify-send "Enabled notifications"

# Screenshots
$hyprshot = $HOME/.local/bin/hyprshot
bindd = , PRINT, Region screenshot, exec, $hyprshot -m region
bindd = ALT, PRINT, Window screenshot, exec, $hyprshot -m window
bindd = SHIFT, PRINT, Monitor screenshot, exec, $hyprshot -m output

# Multimedia keys for media, volume and screen brightness (with SwayOSD)
# These have been disabled since the default ~/.config/hypr/hyprland.conf already binds these
# To activate swayosd, remove the duplicate XF86* binds from hyprland.conf and uncomment the following
#binddl = , XF86AudioNext, Next track, exec, swayosd-client --playerctl next
#binddl = , XF86AudioPause, Pause, exec, swayosd-client --playerctl play-pause
#binddl = , XF86AudioPlay, Play, exec, swayosd-client --playerctl play-pause
#binddl = , XF86AudioPrev, Previous track, exec, swayosd-client --playerctl previous

#binddle = , XF86AudioRaiseVolume, Volume up, exec, swayosd-client --output-volume raise
#binddle = , XF86AudioLowerVolume, Volume down, exec, swayosd-client --output-volume lower
#binddle = , XF86AudioMute, Mute, exec, swayosd-client --output-volume mute-toggle
#binddle = , XF86AudioMicMute, Mute microphone, exec, swayosd-client --input-volume mute-toggle

#binddle = , XF86MonBrightnessUp, Brightness up, exec, swayosd-client --brightness raise
#binddle = , XF86MonBrightnessDown, Brightness down, exec, swayosd-client --brightness lower

