general:grab_focus = 1

cache:enabled = 1

finders:default_finder = desktop
finders:desktop_prefix =
finders:unicode_prefix = :
finders:math_prefix = =
finders:font_prefix = font
finders:desktop_launch_prefix =
finders:desktop_terminal = wezterm
finders:desktop_icons = 1

ui:window_size = 920 340
