#!/bin/bash

dry_run="0"

if [ -z "$XDG_CONFIG_HOME" ]; then
    echo "no xdg config hom"
    echo "using ~/.config"
    XDG_CONFIG_HOME=$HOME/.config
fi

if [ -z "$DEV_ENV" ]; then
    echo "env var DEV_ENV needs to be present"
    exit 1
fi

if [[ $1 == "--dry" ]]; then
    dry_run="1"
fi

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN]: $1"
    else
        echo "$1"
    fi
}

log "env: $DEV_ENV"

update_files() {
    log "copying over files from: $1"
    pushd $1 &> /dev/null
    (
        configs=`find . -mindepth 1 -maxdepth 1 -type d`
        for c in $configs; do
            directory=${2%/}/${c#./}
            log "    removing: rm -rf $directory"

            if [[ $dry_run == "0" ]]; then
                rm -rf $directory
            fi

            log "    copying env: cp $c $2"
            if [[ $dry_run == "0" ]]; then
                cp -r ./$c $2
            fi
        done

    )
    popd &> /dev/null
}

copy() {
    log "removing: $2"
    if [[ $dry_run == "0" ]]; then
        rm $2
    fi
    log "copying: $1 to $2"
    if [[ $dry_run == "0" ]]; then
        cp $1 $2
    fi
}

copy_force() {
    log "removing force: $2"
    if [[ $dry_run == "0" ]]; then
        rm -rf $2
    fi
    log "copying force: $1 to $2"
    if [[ $dry_run == "0" ]]; then
        mkdir -p $2
        cp -r $1 $2
    fi
}

copy_force $XDG_CONFIG_HOME/nvim/. $DEV_ENV/config/nvim/
copy_force $HOME/.vim/. $DEV_ENV/config/vim/
copy_force $XDG_CONFIG_HOME/hypr/. $DEV_ENV/config/hypr/
copy_force $XDG_CONFIG_HOME/waybar/. $DEV_ENV/config/waybar/
copy_force $HOME/.local/scripts/. $DEV_ENV/linux/scripts/
copy $HOME/.local/scripts/dev-env $DEV_ENV/linux/dev-env
copy $HOME/.zshrc $DEV_ENV/config/zsh/.zshrc
copy $HOME/.wezterm.lua $DEV_ENV/config/wezterm/wezterm.lua

rm $DEV_ENV/linux/scripts/dev-env
