#!/usr/bin/env bash

# ==== part of primeagen dev-env script ====
# source on https://raw.githubusercontent.com/ThePrimeagen/dev/refs/heads/master/dev-env

dry_run="0"

if [ -z "$XDG_CONFIG_HOME" ]; then
    echo "no xdg config hom"
    echo "using ~/.config"
    XDG_CONFIG_HOME=$HOME/.config
fi

if [ -z "$DEV_ENV" ]; then
    echo "env var DEV_ENV needs to be present"
    exit 1
fi

if [[ $1 == "--dry" ]]; then
    dry_run="1"
fi

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN]: $1"
    else
        echo "$1"
    fi
}

log "env: $DEV_ENV"

update_files() {
    log "copying over files from: $1"
    pushd $1 &> /dev/null
    (
        configs=`find . -mindepth 1 -maxdepth 1 -type d`
        for c in $configs; do
            directory=${2%/}/${c#./}
            log "    removing: rm -rf $directory"

            if [[ $dry_run == "0" ]]; then
                rm -rf $directory
            fi

            log "    copying env: cp $c $2"
            if [[ $dry_run == "0" ]]; then
                cp -r ./$c $2
            fi
        done

    )
    popd &> /dev/null
}

copy() {
    log "removing: $2"
    if [[ $dry_run == "0" && -f $2 ]]; then
        rm $2
    fi
    log "copying: $1 to $2"
    if [[ $dry_run == "0" ]]; then
        cp $1 $2
    fi
}

copy_force() {
    log "removing force: $2"
    if [[ $dry_run == "0" && -f $2 ]]; then
        rm -rf $2
    fi
    log "copying force: $1 to $2"
    if [[ $dry_run == "0" ]]; then
        cp -r $1 $2
    fi
}

copy_force $DEV_ENV/config/nvim $XDG_CONFIG_HOME/nvim
copy_force $DEV_ENV/config/vim $HOME/.vim

copy_force $DEV_ENV/linux/scripts $HOME/.local/scripts
copy $DEV_ENV/config/zsh/.zshrc $HOME/.zshrc
copy $DEV_ENV/config/wezterm/wezterm.lua $HOME/.wezterm.lua
copy $DEV_ENV/linux/dev-env $HOME/.local/scripts/dev-env

mkdir -p $HOME/.local/bin
