#!/usr/bin/env bash

mkdir -p /tmp/nvim-install
cd /tmp/nvim-install

curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.appimage

chmod u+x nvim-linux-x86_64.appimage

mkdir -p ~/.local/bin
mv nvim-linux-x86_64.appimage ~/.local/bin/nvim

cd -
rm -rf /tmp/nvim-install
